map_server:
  ros__parameters:
    yaml_filename: "/opt/ros/humble/share/turtlebot3_navigation2/maps/map.yaml"

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_pyif_controller::PYIFController"
      python_module: "sicnav_python_example.python_controller.sicnav_controller"
      python_delegates:
        set_plan: "set_plan"
        set_speed_limit: "set_speed_limit"
        compute_velocity_commands: "compute_velocity_commands"

